// <auto-generated />
using DiffFinder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiffFinder.Migrations
{
    [DbContext(typeof(MvcWebAppDbContext))]
    [Migration("20220512212502_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("DiffFinder.Models.DiffrenceInformation", b =>
                {
                    b.Property<int>("DifferenceInformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeftString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RightString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DifferenceInformationId");

                    b.ToTable("DiffrenceInformation");
                });
#pragma warning restore 612, 618
        }
    }
}
